### ISSUE TITLE
Rework members and users behavior

### ISSUE THREAD

**Issue by Xen0Xys** [AmicaleCORE/Karl-API#12]
Change the following :
* [x] Set members table to be only used for memberships.
* [x] Add a origin for a user (for multi association management)
* [x] Now member creation will be on Karl, and discord link will be done using a code

**Comment by loicmaes** [comment]
**Permission management rework:**
- [x] User could now have specific permissions
- [x] User could be moved to another group
- [x] Hard coded permission list
- [x] Manage permissions containing "*"
